name: Atnaujinti TV Programa

on:
  schedule:
    - cron: '0 3 * * *' # Kiekvieną naktį 03:00 val. ryte
  workflow_dispatch: # Leidžia paleisti rankiniu būdu

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Tikrinti koda
        uses: actions/checkout@v4

      - name: Atsisiusti naujausia EPG
        run: |
          # Naudojame naują, veikiantį iptv-org Lietuvos programos šaltinį
          curl -sL https://iptv-org.github.io/epg/guides/lt/lt.xml -o programa.xml

      - name: Issaugoti pakeitimus
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add programa.xml
          git commit -m "Automatinis TV programos atnaujinimas [skip ci]" || exit 0
          git push
